CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "address" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "street" varchar(255) NOT NULL, "number" varchar(20) NOT NULL, "complement" varchar(100) NULL, "city" varchar(100) NOT NULL, "state" varchar(100) NOT NULL, "zip_code" varchar(20) NOT NULL, "country" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "department" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE, "description" text NOT NULL, "price" decimal NOT NULL, "stock" integer unsigned NOT NULL CHECK ("stock" >= 0), "image" varchar(100) NULL);
CREATE TABLE IF NOT EXISTS "user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "employee" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "birthdate" date NOT NULL, "departament_id" bigint NOT NULL REFERENCES "department" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL UNIQUE REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "user_groups_customuser_id_group_id_69b568ae_uniq" ON "user_groups" ("customuser_id", "group_id");
CREATE INDEX "user_groups_customuser_id_246bd336" ON "user_groups" ("customuser_id");
CREATE INDEX "user_groups_group_id_b76f8aba" ON "user_groups" ("group_id");
CREATE UNIQUE INDEX "user_user_permissions_customuser_id_permission_id_2f47aad7_uniq" ON "user_user_permissions" ("customuser_id", "permission_id");
CREATE INDEX "user_user_permissions_customuser_id_3b468234" ON "user_user_permissions" ("customuser_id");
CREATE INDEX "user_user_permissions_permission_id_9deb68a3" ON "user_user_permissions" ("permission_id");
CREATE INDEX "comercial_employee_departament_id_05c99173" ON "employee" ("departament_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "prod_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantity" integer unsigned NOT NULL CHECK ("quantity" >= 0), "order_id" bigint NOT NULL REFERENCES "comercial_order" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "product" ("id") DEFERRABLE INITIALLY DEFERRED, "unit_price" decimal NOT NULL);
CREATE UNIQUE INDEX "prod_order_order_id_product_id_fe5ce81b_uniq" ON "prod_order" ("order_id", "product_id");
CREATE INDEX "prod_order_order_id_1ecf8077" ON "prod_order" ("order_id");
CREATE INDEX "prod_order_product_id_afc64fef" ON "prod_order" ("product_id");
CREATE TABLE IF NOT EXISTS "customer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "address_id" bigint NOT NULL REFERENCES "address" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL UNIQUE REFERENCES "user" ("id") DEFERRABLE INITIALLY DEFERRED, "active" bool NOT NULL);
CREATE INDEX "customer_address_id_e405cf96" ON "customer" ("address_id");
CREATE TABLE IF NOT EXISTS "comercial_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "order_date" datetime NOT NULL, "customer_id" bigint NOT NULL REFERENCES "customer" ("id") DEFERRABLE INITIALLY DEFERRED, "notes" text NULL, "status" varchar(20) NOT NULL, "delivery_fee" decimal NOT NULL, "discount_type" varchar(10) NOT NULL, "discount_value" decimal NOT NULL, "confirmed_total" decimal NULL, "confirmed_date" datetime NULL, "free_delivery" bool NOT NULL);
CREATE INDEX "comercial_order_customer_id_604b34a2" ON "comercial_order" ("customer_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
