# Generated by Django 5.2.3 on 2025-06-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_order_notes_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Preço Unitário'),
            preserve_default=False,
        ),
    ]
