# Generated by Django 5.2.3 on 2025-06-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_order_discount_type_order_discount_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
