# Generated by Django 5.2.3 on 2025-06-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_alter_address_options_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
