# Generated by Django 5.2.3 on 2025-06-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Confirmado'),
        ),
    ]
