# Generated by Django 5.2.3 on 2025-06-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_order_confirmed_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação'),
        ),
        migrations.AddField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Entrega Grátis'),
        ),
    ]
