# Generated by Django 5.2.3 on 2025-06-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_alter_order_status_delete_delivery_delete_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departament',
            new_name='department',
        ),
    ]
